server:
  port: 8082
spring:
  application:
    name: backend-post
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306
  cloud:
    loadbalancer:
      enabled: true
#更改主机实例ID名
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    #鼠标悬停时显示主机ip地址
    prefer-ip-address: true
  #表示是否将自己注册进Eureka，默认为true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/